# Generated by Django 5.2.3 on 2025-07-05 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatPais',
            fields=[
                ('id_pais', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cat_pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatRecord',
            fields=[
                ('id_record', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_record', models.CharField(max_length=255)),
                ('descripcion_record', models.CharField(max_length=500)),
                ('img_record', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cat_records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatSello',
            fields=[
                ('id_sello', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_sello', models.CharField(max_length=100)),
                ('descripcion_sello', models.CharField(max_length=500)),
                ('label', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cat_sellos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatArtistas',
            fields=[
                ('id_artista', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_artista', models.CharField(max_length=100)),
                ('id_pais', models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.CASCADE, to='api.catpais')),
            ],
            options={
                'db_table': 'cat_artistas',
                'managed': True,
            },
        ),
    ]
